# Generated by Django 3.2.3 on 2021-05-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
