version: "3.8"

services: 
    web:
        build: .
        command: python manage.py runserver 0:8000
 
        volumes:
            - .:/code
            - /db.sqlite3
        ports:
            - 8000:8000
    