version: "3.8"

services: 
    web:
        build: .
        command: python manage.py runserver 0:8000
 
        volumes:
            - .:/code
            - /db.sqlite3
        ports:
            - 8000:8000
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres