# Generated by Django 3.2.3 on 2021-06-12 04:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborator', '0001_initial'),
        ('company', '0001_initial'),
        ('departament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=300)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('final_date', models.DateField(blank=True, null=True)),
                ('file_task', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.BooleanField(choices=[(False, 'Não Concluido'), (True, 'Concluido')], default=False)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collaborator.collaborator')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departament.departament')),
            ],
        ),
    ]
