# Generated by Django 3.2.3 on 2021-06-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskapi',
            name='date',
        ),
    ]
