# Generated by Django 3.2.3 on 2021-06-14 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0003_alter_collaborator_options'),
        ('task', '0003_remove_taskapi_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskapi',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collaborator.collaborator'),
        ),
    ]
