# Generated by Django 3.2.3 on 2021-06-07 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborator', '0007_collaborator_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collaborator.collaborator')),
            ],
        ),
    ]
