# Generated by Django 3.2.3 on 2021-06-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='modulo',
            field=models.IntegerField(choices=[(0, 'Modulo não declarado'), (1, 'Collaborator'), (2, 'Company'), (3, 'Departament'), (4, 'Documents'), (5, 'Hora Extra')], default=0),
        ),
    ]
