# Generated by Django 3.2.3 on 2021-05-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
