# Generated by Django 3.1.8 on 2021-05-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterExtraHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collaborator.collaborator')),
            ],
        ),
    ]
