# Generated by Django 3.2.3 on 2021-06-12 04:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterExtraHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(default='Em Analise', max_length=30)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collaborator.collaborator')),
            ],
        ),
    ]
