# Generated by Django 3.2.3 on 2021-06-30 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0004_auto_20210616_2009'),
        ('company', '0004_alter_company_code_company'),
        ('register_extra_hour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_logout', models.DateTimeField()),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collaborator.collaborator')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
        ),
    ]
