# Generated by Django 3.2.3 on 2021-05-27 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0002_auto_20210527_0416'),
        ('register_extra_hour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerextrahour',
            name='collaborator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='collaborator.collaborator'),
            preserve_default=False,
        ),
    ]
