# Generated by Django 3.2.3 on 2021-05-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_extra_hour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerextrahour',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='registerextrahour',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
