# Generated by Django 3.2.3 on 2021-05-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_extra_hour', '0002_registerextrahour_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerextrahour',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
    ]
