# Generated by Django 3.2.3 on 2021-06-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_extra_hour', '0002_registerpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerpoint',
            name='horas_trabalhadas',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
