# Generated by Django 3.2.3 on 2021-05-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_extra_hour', '0003_registerextrahour_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerextrahour',
            name='date',
        ),
    ]
