# Generated by Django 3.2.3 on 2021-06-30 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_code_company'),
        ('register_extra_hour', '0003_registerpoint_horas_trabalhadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerpoint',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerpoint',
            name='horas_trabalhadas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
