# Generated by Django 3.2.3 on 2021-06-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0004_auto_20210616_2009'),
        ('register_extra_hour', '0004_auto_20210630_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerpoint',
            name='collaborator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collaborator.collaborator'),
        ),
    ]
