# Generated by Django 3.2.3 on 2021-07-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_code_company'),
        ('collaborator', '0004_auto_20210616_2009'),
        ('register_extra_hour', '0006_auto_20210701_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterPoint',
            new_name='Point',
        ),
    ]
