# Generated by Django 3.2.3 on 2021-07-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_extra_hour', '0007_rename_registerpoint_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerextrahour',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
