# Generated by Django 3.2.3 on 2021-05-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_extra_hour', '0007_alter_registerextrahour_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerextrahour',
            name='status',
            field=models.CharField(default='Em Analise', max_length=30),
        ),
    ]
