# Generated by Django 3.2.3 on 2021-06-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210621_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code_company',
            field=models.CharField(default='F2C1FD', max_length=30),
        ),
    ]
