# Generated by Django 3.2.3 on 2021-05-30 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_auto_20210530_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gerente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
