# Generated by Django 3.2.3 on 2021-05-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cidade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
