# Generated by Django 3.2.3 on 2021-07-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_company_code_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code_company',
            field=models.CharField(default='7CA18D', max_length=30),
        ),
    ]
