# Generated by Django 3.2.3 on 2021-07-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_alter_company_code_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code_company',
            field=models.CharField(default='25F49F', max_length=30),
        ),
    ]
