# Generated by Django 3.2.3 on 2021-06-12 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departament', '__first__'),
        ('company', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('total_horas', models.FloatField(default=0.0)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('logged', models.BooleanField(choices=[(False, 'Offline'), (True, 'Online')], default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('departaments', models.ManyToManyField(blank=True, to='departament.Departament')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('gerente_geral', 'administrative functions in system.'), ('funcionario', 'user common is system'), ('lider_departament', 'lider in departaments')],
            },
        ),
    ]
