# Generated by Django 3.2.3 on 2021-05-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0002_auto_20210530_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='total_horas',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
