# Generated by Django 3.2.3 on 2021-06-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0002_alter_collaborator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborator',
            options={},
        ),
    ]
