# Generated by Django 3.2.3 on 2021-05-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '__first__'),
        ('collaborator', '0003_alter_collaborator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
    ]
