# Generated by Django 3.2.3 on 2021-05-29 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departament', '0001_initial'),
        ('collaborator', '0004_alter_collaborator_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='departaments',
            field=models.ManyToManyField(blank=True, null=True, to='departament.Departament'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
