# Generated by Django 3.2.3 on 2021-07-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0004_auto_20210616_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
