# Generated by Django 3.2.3 on 2021-05-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0004_alter_collaborator_total_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='total_horas',
            field=models.FloatField(default=0.0),
        ),
    ]
