# Generated by Django 3.2.3 on 2021-06-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0005_alter_collaborator_total_horas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborator',
            options={'permissions': [('gerente_geral', 'ceo')]},
        ),
    ]
