# Generated by Django 3.2.3 on 2021-05-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0001_initial'),
        ('collaborator', '0005_auto_20210528_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='departaments',
            field=models.ManyToManyField(blank=True, to='departament.Departament'),
        ),
    ]
