# Generated by Django 3.2.3 on 2021-06-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0006_alter_collaborator_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
