# Generated by Django 3.2.3 on 2021-06-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0007_collaborator_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='logged',
            field=models.BooleanField(default=0),
        ),
    ]
