# Generated by Django 3.2.3 on 2021-06-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0008_collaborator_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='logged',
            field=models.BooleanField(choices=[(0, 'Offline'), (1, 'Online')], default=0),
        ),
    ]
